# -*- coding: utf-8 -*-
"""TravelLens.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ndpmBYGG2IQrKmkRJ0GC_34frxC_zGnq
"""

from google.colab import drive
drive.mount('/content/drive')

from numpy import argmax
from tensorflow.nn import softmax
from tensorflow.python.ops.gen_array_ops import expand_dims
from keras.utils.image_utils import img_to_array
import keras
from PIL import Image
# from tensorflow.keras.utils import Image
import numpy as np

# Path ke file model H5
model_path = '/content/drive/MyDrive/model_cnn_TravelLens.h5'

# Load model dari file H5
model = keras.models.load_model(model_path)

# Contoh penggunaan model
input_data = '/content/aug_0_288.jpg'  # Isi dengan data masukan Anda sebagai array NumPy
img = Image.open(input_data)
img = img.resize((224,224))
img_array = img_to_array(img)
img_array = expand_dims(img, 0)

pred = model.predict(img_array)
score = softmax(pred[0])

# Lakukan sesuatu dengan output model
labels = ['Bedugul',
          'Garuda Wisnu Kencana',
          'Ground Zero','Monumen Bajra Sandi',
          'Patung Dewa Ruci',
          'Patung Nakula Sadewa',
          'Patung Satria Gatotkaca',
          'Tanah Lot',
          'Vihara Dharma Giri']
predicted_index = np.argmax(score)
predicted_label = labels[predicted_index]
print(predicted_label)

